# Generated by Django 5.0 on 2023-12-17 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(upload_to='uploads/')),
                ('customer', models.CharField(max_length=30)),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('anatator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='uploads/')),
                ('length', models.IntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, default=' ', null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.audio')),
            ],
        ),
    ]
