# Generated by Django 5.0 on 2023-12-18 19:28

import audios.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_alter_audio_anatator'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='number_segments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiosegment',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audios.audio'),
        ),
        migrations.AlterField(
            model_name='audiosegment',
            name='transcript',
            field=models.TextField(blank=True, default=' ', null=True, validators=[audios.validators.check_character_set, audios.validators.check_space, audios.validators.check_capital_letters, audios.validators.check_the_end_text]),
        ),
    ]
